language: haskell
ghc:
  - 7.8
  - 7.6
install:
  - cabal install cabal-install
  - export PATH="$HOME/.cabal/bin:$PATH"
  - cabal install --only-dependencies --enable-tests --force-reinstalls
sudo: false
